server:
    port: 3000

spring:

    datasource:
        dataSourceClassName: org.mariadb.jdbc.MySQLDataSource
        url: jdbc:mysql://localhost:3306/test

        username: root
        password:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true

    thymeleaf:
        cache: false
        mode: LEGACYHTML5
